version: "3"

services:

  postresql:
    image: postgres:alpine
    volumes:
# Doesn't work yet
#      - ./docker/pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  kinto:
    build: ./docker/kinto-club
    links:
    - postresql
#    - clubexpressions.eu.auth0.com
    ports:
    - "8888:8888"
    environment:
      KINTO_CACHE_BACKEND: kinto.core.cache.postgresql
      KINTO_CACHE_URL: postgres://postgres:postgres@postresql/postgres
      KINTO_STORAGE_BACKEND: kinto.core.storage.postgresql
      KINTO_STORAGE_URL: postgres://postgres:postgres@postresql/postgres
      KINTO_PERMISSION_BACKEND: kinto.core.permission.postgresql
      KINTO_PERMISSION_URL: postgres://postgres:postgres@postresql/postgres
    volumes:
      - ./kinto:/etc/kinto

  traefik:
    image: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/traefik/:/etc/traefik/:ro
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    links:
      - kinto

#  clubexpressions.eu.auth0.com:
#    image: httpd:alpine
#    volumes:
#      - ./docker/clubexpressions.eu.auth0.com:/usr/local/apache2/htdocs
